### PR TITLE
Issue/466 swap gsp name

### LINKED ISSUE #466: Swap name order on Sites aggregation regions
Dan via Vercel Preview:

>For the names of the Regions, could we swap the around so they are East (UKPN), South West (WPD) etc?  The reason is the region names are the primary identifier, and are fixed, but the owners of the franchises could change over time.

### PR DESCRIPTION
**Pull request by peterdudfield**
# Pull Request

## Description

Swap DNO name order

before

Screenshot 2024-05-14 at 13 05 35

now
Screenshot 2024-05-14 at 13 05 01

Fixes #466 

## How Has This Been Tested?

Looked at the new vercel branch + added some unit tests

- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by rachel-labri-tipton** [comment]
hi @peterdudfield, I'm just having a look at this and wondering what the difference is between `SSE` and `Southern (SSE)`. I  probably just don't know the DNO's well enough.

**Comment by peterdudfield** [comment]
> hi @peterdudfield, I'm just having a look at this and wondering what the difference is between `SSE` and `Southern (SSE)`. I  probably just don't know the DNO's well enough. 

Yea, I'm not sure either

https://github.com/openclimatefix/quartz-frontend/issues/466

I've put all the names from the api in this issue

**Review by braddf — COMMENTED** [review]
@peterdudfield Is this new name format function intentionally trimming to Region names to only the first word? E.g. `WPD (South West)` becomes `South (WPD)` which is not quite the same information

**Comment by peterdudfield** [comment]
> @peterdudfield Is this new name format function intentionally trimming to Region names to only the first word? E.g. `WPD (South West)` becomes `South (WPD)` which is not quite the same information

ah good spot, not I think it lost a word there somewhere. 
Let me fix that

**Pull request merged**
