### PR TITLE
Quartz Energy v0.1.1 – Auth + Forecast Horizon Select

### LINKED ISSUE #504: Auth0

### LINKED ISSUE #519: India: X forecast
## Detailed Description
It would be great to have an option that selects what type of forecast the user is looking at
The two options now in the API are
- DA
- latest
- 3 hours
- 1.5 hours

## Context
- Nice for users to be able to look back at DA forecast

## Possible Implementation
- drop down menu with those two options,
- option gets passed through to API call

### PR DESCRIPTION
**Pull request by braddf**
# Pull Request – **RELEASE**

## Features and Changes

- Add Auth to Quartz Energy
  - Fixes #504
- Add feature to select forecast horizon in Quartz Energy UI
  - Fixes #519

## Caveats and Dependencies

- [x] Auth vars need to be set for `production` environment in Vercel, to the same as the `Preview – staging` environment vars.

## How Has This Been Tested?

Locally against `local` and `dev` APIs, and on [dev deploy](https://dev.quartz.energy) and [staging deploy](https://staging.quartz.energy)

- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
anything changed on nowcasting-app? 
node CI build failing?

**Review by peterdudfield — APPROVED** [review]

**Comment by peterdudfield** [comment]
Could you add in the PR descirption a link to the github issue for auth?

**Comment by braddf** [comment]
@peterdudfield Yep all good re the above:
- minimal changes to `nowcasting-app` files to allow it to build/render consistently (server- vs. client-side rendering issue), but if it builds it should be identical as is just about how the imports are happening;
- the Node CI will fail at the moment until I finish getting the end-to-end (Cypress) tests working in the CI, hopefully soon as I think I worked out the commands a few weeks ago.

**Comment by braddf** [comment]
N.B. `preview` branches are currently being funny with the Auth redirect, so I may have done that differently to `nowcasting-app` as they try to redirect back to the `AUTH0_BASE_URL` if set, i.e. `staging.quartz.app` in this case, which is not where it came from... I'll check it out in a bit, but the main `staging` URL on the proper subdomain works fine because it's explicitly set. 👍

**Pull request merged**
